apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-daemon
  namespace: dagster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagster-daemon
  template:
    metadata:
      labels:
        app: dagster-daemon
    spec:
      containers:
        - name: dagster-daemon
          image: {{ images.dagster_daemon }}
          command: ["dagster-daemon", "run"]
          volumeMounts:
            - name: dagster-instance
              mountPath: /opt/dagster/dagster_home/
            - name: dagster-workspace
              mountPath: /opt/dagster/workspace/workspace.yaml
              subPath: workspace.yaml
      volumes:
        - name: dagster-instance
          configMap:
            name: dagster-instance-cm
        - name: dagster-workspace
          configMap:
            name: dagster-workspace-cm
