# Site A PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-A
  namespace: datpipe-A
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
