apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-A
  namespace: datpipe-A
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-A
  template:
    metadata:
      labels:
        app: postgres-A
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret-A
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-A
