# Site B PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-B
  namespace: datpipe-B
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
