apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-B
  namespace: datpipe-B
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-B
  template:
    metadata:
      labels:
        app: postgres-B
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret-B
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-B
