apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dagster
  namespace: dagster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dagster
  template:
    metadata:
      labels:
        app: postgres-dagster
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret-dagster
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-dagster
